#!/usr/bin/env python

# full width horizontal bar at top to search
# left column with current results: name, mod date, summary, tags
# right column with text of currently selected note

# * typing in the search bar:
# - press enter: focus jumps to note if ANYTHING is selected. if nothing is
# selected, enter creates a new note with the current string as its name.
# - esc clears the search entry, esc again jumps to list
# - up and down changes currently selected list
# * in note conten area
# - esc goes back to notes list.

# http://www.scribd.com/doc/91277952/Simple-Note-API-v2-1-3
# this also has a sync algorithm!

# 1. finish implementing search
# 2. note editing
#   a) saving to disc: remember lmodified or whatever.
#   b) syncing with simplenote


import ConfigParser
from notes_db import NotesDB
import os
import sys
from utils import SubjectMixin
import view

class Config:
    def __init__(self, cfg_fname, defaults):
        # allow_no_value=True means we'll just get None for undefined values
        cp = ConfigParser.SafeConfigParser(defaults, allow_no_value=True)
        cp.read(cfg_fname)
        self.sn_username = cp.get('default', 'sn_username')
        self.sn_password = cp.get('default', 'sn_password')
        self.db_path = cp.get('default', 'db_path')
        
class NotesListModel(SubjectMixin):
    def __init__(self):
        # call mixin ctor
        SubjectMixin.__init__(self)
        
        self.list = []
        
    def set_list(self, alist):
        self.list = alist
        self.notify_observers('list_change', None)
    
class NoteContentModel(SubjectMixin):
    def __init__(self):
        # call mixin ctor
        SubjectMixin.__init__(self)
        
        self.content = None
        
    def set_content(self, content):
        """Call this when this is a new note.
        """
        self.content = content
        self.notify_observers('content:set', None)

    def update_content(self, content):
        """Call this when changes are made to the current note.

        Only differes from set_content in the event that is fired.
        """
        self.content = content
        self.notify_observers('content:update', None)
        
class Controller:
    """Main application class.
    """
    
    def __init__(self):
        # setup appdir
        if hasattr(sys, 'frozen') and sys.frozen:
            self.appdir, _ = os.path.split(sys.executable)
        else:
            dirname = os.path.dirname(sys.argv[0])
            if dirname and dirname != os.curdir:
                self.appdir = dirname
            else:
                self.appdir = os.getcwd()
        
        # should probably also look in $HOME
        cfg_defaults = {'appdir' : self.appdir}
        self.config = Config(os.path.join(self.appdir, 'nvPY.cfg'), cfg_defaults)
        
        # read our database of notes into memory
        # and sync with simplenote.
        self.notes_db = NotesDB(self.config.db_path, self.config.sn_username, self.config.sn_password)
        #self.notes_db.sync_full()

        self.notes_list_model = NotesListModel()
        self.note_content_model = NoteContentModel()
        
        # create the interface
        self.view = view.View(self, self.notes_list_model, self.note_content_model)
        # we want to be notified when the user does stuff
        self.view.add_observer(self.observer_view)
        
        # nn is a list of (key, title, modifydate) objects
        nn = self.notes_db.get_note_names()
        # this will trigger the list_change event
        self.notes_list_model.set_list(nn)

        self.selected_note = None
        # FIXME: no notes?
        self.view.select_note(0)
        
    def get_version(self):
        return "0.2"

    def quit(self):
        self.view.close()
        
    def main_loop(self):
        self.view.main_loop()
        
    def observer_view(self, view, evt_type, evt):
        if evt_type == 'note:select':
            self.select_note(evt.sel)
            
        elif evt_type == 'change:entry':
            # la la
            print evt.value
            
    def select_note(self, idx):
        key = self.notes_list_model.list[idx].key
        c = self.notes_db.get_note_content(key)
        self.note_content_model.set_content(c)

def main():
    controller = Controller()
    controller.main_loop()
    

if __name__ == '__main__':
    main()

